/**
 * Created by Romero on 15/08/2015.
 */
public class Problem2 {
    /**
     *
     * Problem 2 - Even Fibonacci numbers
     * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
     * By starting with 1 and 2, the first 10 terms will be:
     *
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     *
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
     * find the sum of the even-valued terms.
     *
     */
    public static void evenFibonacciNumbers() {
        long previous = 0;
        long current = 1;
        long next = previous + current;
        long limit = 4000000L;
        long total = 0;

        while (current < limit) {
            next = current + previous;

            previous = current;
            current = next;

            next = 0;

            if ((current % 2) == 0) {
                total += current;
                System.out.print(current + "; ");
            }
        }

        System.out.println("\n\n > Total: " + total);
    }
}
